# Generated by Django 5.1.3 on 2025-09-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyfirstApp', '0006_contact_delete_followerscount_delete_likepost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emial',
            new_name='email',
        ),
    ]
